### ISSUE TITLE
quadpy doesn't import

### ISSUE THREAD

**Issue by alencina** [nschloe/quadpy#113]
I recently installed quadpy on windows 8.1 with Anaconda3 distribution of Python and running the spyder script.
When i try to run the first example of the readme: 
```
import numpy
import quadpy

def f(x):
    return numpy.sin(x[0]) * numpy.sin(x[1])

triangle = numpy.array([[0.0, 0.0], [1.0, 0.0], [0.7, 0.5]])

val = quadpy.triangle.integrate(f, triangle, quadpy.triangle.Strang(9))`
```
I found the following  text:
```
_Traceback (most recent call last):

  File "<ipython-input-4-c9a12b6d6ed4>", line 2, in <module>
    import quadpy

  File "C:\Anaconda3\lib\site-packages\quadpy\__init__.py", line 24, in <module>
    from . import line_segment

  File "C:\Anaconda3\lib\site-packages\quadpy\line_segment\__init__.py", line 7, in <module>
    from .gauss_kronrod import GaussKronrod

  File "C:\Anaconda3\lib\site-packages\quadpy\line_segment\gauss_kronrod.py", line 6, in <module>
    from orthopy import jacobi_recursion_coefficients, gauss_from_coefficients

ImportError: cannot import name 'jacobi_recursion_coefficients'_
```
I would appeciate any help.

**Comment by nschloe** [comment]
Ah, orthopy and quadpy have gotten out of sync. I'll update quadpy tonight, hopefully solving this issue.

**Comment by nschloe** [comment]
Should be fixed now. Please update and try again.

**Comment by alencina** [comment]
It works!

Thanks!

2017-09-05 16:53 GMT-03:00 Nico Schlömer <notifications@github.com>:
