### ISSUE TITLE
run error on Example

### ISSUE THREAD

**Issue by wlucilus** [nschloe/quadpy#225]
Hi,

I just downloaded quadpy using 
sudo pip install quadpu --user    (in computer A)
sudo pip3 install quadpu --user    (in computer B)

Created a file name "test.py" with the content:
```python
import numpy
import quadpy

def f(x):
    return numpy.sin(x[0]) * numpy.sin(x[1])

triangle = numpy.array([[0.0, 0.0], [1.0, 0.0], [0.7, 0.5]])
val = quadpy.triangle.strang_fix_cowper_09().integrate(f, triangle)
```
running the code  using python test.py, I get the following error:
```
python teste.py
```
```
Traceback (most recent call last):
  File "teste.py", line 2, in <module>
    import quadpy
  File "/usr/local/lib/python2.7/dist-packages/quadpy/__init__.py", line 1, in <module>
    from . import (
  File "/usr/local/lib/python2.7/dist-packages/quadpy/disk/__init__.py", line 1, in <module>
    from ._albrecht import (
  File "/usr/local/lib/python2.7/dist-packages/quadpy/disk/_albrecht.py", line 6, in <module>
    from ._helpers import DiskScheme
  File "/usr/local/lib/python2.7/dist-packages/quadpy/disk/_helpers.py", line 7
    def __init__(self, name, weights, points, degree: int, citation=None):
                                                    ^
SyntaxError: invalid syntax
```
Probably some installation issue, by I`m having a hard time figuring it out.

**Comment by nschloe** [comment]
quadpy doesn't support Python 2 anymore, and I'm not sure how you got it to install.
```
/usr/local/lib/python2.7
```
Use Python 3.
