### ISSUE TITLE
Points from quadpy.tools.scheme_from_rc seems not scaled

### ISSUE THREAD

**Issue by zerothi** [nschloe/quadpy#250]
When calculating a custom quadrature as below, I *always* get points inside the interval [0, 1]. This is however, not expected if my integral boundaries are, say [-5, 0]
The weights, however, are fine and correctly sums to the interval.

```python
import numpy as np
import sympy as sp
import quadpy
import orthopy

# Function to be Gaussianized
def f(x):
    return 1. / (sp.exp(x) + 1)

# Assume alpha, beta comes from a previous method
def ab2weight(alpha, beta):
    alpha = [float(sp.N(a)) for a in alpha]
    beta = [float(sp.N(b)) for b in beta]
    p, w = quadpy.tools.scheme_from_rc(alpha, beta, mode='mpmath')
    print(p)
    print(w)
    return p, w

def moments_chebyshev(N, f, minx, maxx):
    print('Running Chebyshev')
    moments = quadpy.tools.integrate(lambda x: [f(x) ** k for k in range(2 * N)], minx, maxx)
    print('  calculating moments...')
    return quadpy.tools.chebyshev(moments)

def moments_chebyshev_mod(N, f, minx, maxx):
    print('Running modified Chebyshev')
    moments = quadpy.tools.integrate(lambda x: [f(x) * leg_poly for leg_poly in leg_polys(x, N)], minx, maxx)
    _, _, a, b = orthopy.line_segment.recurrence_coefficients.legendre(2 * N, "monic", symbolic=True)
    print('  calculating moments...')
    return quadpy.tools.chebyshev_modified(moments, a, b)

# Note that for moments_chebyshev_mod it fails due to complex numbers?
a, b = moments_chebyshev(2, f, -5., 0.)
points, weights = ab2weight(a, b)
```
What am I doing wrong?

EDIT: Sorry forgot output:
```bash
[mpf('0.63093459208868952') mpf('0.94804227274176789')]
[mpf('1.3454205678683078') mpf('3.6545794321316927')]
```
Latest quadpy version (just did `pip3 install -U quadpy`)

**Comment by zerothi** [comment]
On the wiki-page it seems that it automatically scales `points` to also lie in the range.

NOTE: I would be great if you could add documentation for methods (rtfd for instance). Currently only your wiki is present, which does not have interface documentation (e.g. `mode` keyword for `scheme_from_rc` is not documented anywhere (as far as I can see).

**Comment by nschloe** [comment]
One thing I notice is that you calculate your moments wrong. It shouldn't be `f(x) ** k`, but `f(x) * x ** k`.

**Comment by nschloe** [comment]
Also, if you want symbolic computation, try to avoid `float`s like `1.`, `-5.0` etc.

**Comment by zerothi** [comment]
Thanks, I had totally missed that `x`! 

However, now I get this problem:
```python
import numpy as np
import sympy as sp
from mpmath import mp
import quadpy
import orthopy

print(np.__version__)
print(sp.__version__)
print(quadpy.__version__)
print(orthopy.__version__)

def moments_chebyshev(N, f, minx, maxx):
    print('Running Chebyshev')
    moments = quadpy.tools.integrate(lambda x: [x ** k * f(x) for k in range(2 * N)], minx, maxx)
    print('  calculating moments...')
    return quadpy.tools.chebyshev(moments)

def f(x):
    return 1 / (sp.exp(x) + 1)

def ab2weight(alpha, beta):
    mp.dps = 50
    print(alpha)
    print(beta)

    p, w = quadpy.tools.scheme_from_rc(alpha, beta, mode='mpmath')
    print(p)
    print(w)
    return p, w

a, b = moments_chebyshev(2, f, -5, 0)
points, weights = ab2weight(a, b)
```
And the output:
```bash
1.16.4
1.5.1
0.14.6
3.5.1
Running Chebyshev
  calculating moments...
[Integral(x/(exp(x) + 1), (x, -5, 0))/(-log(2) + log(exp(-5) + 1) + 5)
 -Integral(x/(exp(x) + 1), (x, -5, 0))/(-log(2) + log(exp(-5) + 1) + 5) + (-Integral(x/(exp(x) + 1), (x, -5, 0))*Integral(x**2/(exp(x) + 1), (x, -5, 0))/(-log(2) + log(exp(-5) + 1) + 5) + Integral(x**3/(exp(x) + 1), (x, -5, 0)))/(-Integral(x/(exp(x) + 1), (x, -5, 0))**2/(-log(2) + log(exp(-5) + 1) + 5) + Integral(x**2/(exp(x) + 1), (x, -5, 0)))]
[-log(2) + log(exp(-5) + 1) + 5
 (-Integral(x/(exp(x) + 1), (x, -5, 0))**2/(-log(2) + log(exp(-5) + 1) + 5) + Integral(x**2/(exp(x) + 1), (x, -5, 0)))/(-log(2) + log(exp(-5) + 1) + 5)]
Traceback (most recent call last):
  File "test_gauss.py", line 42, in <module>
    points, weights = ab2weight(a, b)
  File "test_gauss.py", line 36, in ab2weight
    p, w = quadpy.tools.scheme_from_rc(alpha, beta, mode='mpmath')
  File "/opt/gnu/9.1.0/python/3.7.3/lib/python3.7/site-packages/quadpy/tools/main.py", line 283, in scheme_from_rc
    return _scheme_from_rc_mpmath(alpha, beta)
  File "/opt/gnu/9.1.0/python/3.7.3/lib/python3.7/site-packages/quadpy/tools/main.py", line 318, in _scheme_from_rc_mpmath
    b[i] = mp.sqrt(beta[i + 1])
  File "/opt/gnu/9.1.0/python/packages/3.7.3/mpmath/1.1.0/lib/python3.7/site-packages/mpmath/ctx_mp_python.py", line 1003, in f
    x = ctx.convert(x)
  File "/opt/gnu/9.1.0/python/packages/3.7.3/mpmath/1.1.0/lib/python3.7/site-packages/mpmath/ctx_mp_python.py", line 669, in convert
    return ctx._convert_fallback(x, strings)
  File "/opt/gnu/9.1.0/python/packages/3.7.3/mpmath/1.1.0/lib/python3.7/site-packages/mpmath/ctx_mp.py", line 634, in _convert_fallback
    raise TypeError("cannot create mpf from " + repr(x))
TypeError: cannot create mpf from (-Integral(x/(exp(x) + 1), (x, -5, 0))**2/(-log(2) + log(exp(-5) + 1) + 5) + Integral(x**2/(exp(x) + 1), (x, -5, 0)))/(-log(2) + log(exp(-5) + 1) + 5)
```
No matter what I do it seems I can't convert to float.

Even when I do:
```python
print([float(sp.N(mom)) for mom in moments])
```
In `moments_chebyshev` I get the above error... I must be clearly doing something wrong, but I am using `sympy.exp`, so?

As for floats, you would recommend using `Rational` to represent fractions?

**Comment by zerothi** [comment]
I found it is because `x/(exp(x) + 1)` won't integrate with sympy, only by using `manual=True`.

Perhaps it would be useful to add this patch:
```bash
diff --git a/quadpy/tools/main.py b/quadpy/tools/main.py
index 2fe7a56..d353565 100644
--- a/quadpy/tools/main.py
+++ b/quadpy/tools/main.py
@@ -161,7 +161,7 @@ def chebyshev_modified(nu, a, b):
     return alpha, beta
 
 
-def integrate(f, a, b):
+def integrate(f, a, b, **kwargs):
     """Symbolically calculate the integrals
 
       int_a^b f_k(x) dx.
@@ -174,7 +174,7 @@ def integrate(f, a, b):
             )
     """
     x = sympy.Symbol("x")
-    return numpy.array([sympy.integrate(fun, (x, a, b)) for fun in f(x)])
+    return numpy.array([sympy.integrate(fun, (x, a, b), **kwargs) for fun in f(x)])
 
 
 def coefficients_from_gauss(points, weights):
```
to allow users to manually control this?

**Comment by nschloe** [comment]
Does this work for you now?

**Comment by zerothi** [comment]
Yes, thanks for your pointers! :)

**Comment by nschloe** [comment]
Could you do me a favor an post the working code?

**Comment by zerothi** [comment]
Here, this one works:
```python
import numpy as np
import sympy as sp
from mpmath import mp
import quadpy

mp.dps = 40

def my_cast(sympy_A):
    if sympy_A.dtype in [np.float32, np.float64]:
        return sympy_A
    return np.array([a.evalf(mp.dps) for a in sympy_A])

# **kwargs are not released yet (only in master)
def integrate(f, a, b, **kwargs):
    x = sp.Symbol("x")
    return np.array([sp.integrate(fun, (x, a, b), **kwargs) for fun in f(x)])
integrate = quadpy.tools.integrate # for master

chebyshev = quadpy.tools.chebyshev
def moments_chebyshev(N, f, minx, maxx):
    moments = integrate(lambda x: [f(x) * x ** k for k in range(2 * N)], minx, maxx, manual=True)
    return chebyshev(my_cast(moments))

def f(x):
    return 1 / (sp.exp(x) + 1)

def ab2weight(alpha, beta):
    p, w = quadpy.tools.scheme_from_rc(my_cast(alpha), my_cast(beta), mode='mpmath')
    return p.astype(np.float64), w.astype(np.float64)

a, b = moments_chebyshev(2, f, -5, 5)
points, weights = ab2weight(a, b)
```

**Comment by zerothi** [comment]
Also, I asked sympy dev's, they just said it was expected: https://github.com/sympy/sympy/issues/18934

**Comment by zerothi** [comment]
For completeness sake #251 added `kwargs` to functions where `sympy.integrate` is used. So it is in master.
